### PR TITLE
Fix crunching of dates

### PR DESCRIPTION
**Pull request by andrewprins**
It appears that the fix [made here](https://github.com/banterfm/graphql-crunch/issues/13) was lost at some point, probably in the merge due to conflicts with the also-added array check.

Adds the check back in and also adds tests to help avoid future regression

### CODE REVIEW

**Comment by stevekrenzel** [comment]
Hey, sorry I somehow missed this PR! 😅 Let me give this a look tonight. I just want to think through the implications here, as `crunch` is designed to operate on JSON blobs and `Date` is not part of the `JSON` spec.

**Comment by paul-pop** [comment]
@stevekrenzel did you get a chance to look over this?

**Comment by ajRiverav** [comment]
@stevekrenzel

**Review by stevekrenzel — APPROVED** [review]
Thanks for fixing this. I'm embarrassed it took so long for me to merge, but it is appreciated.

**Pull request merged**
